# Generated by Django 5.1.1 on 2024-09-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0002_comment_user_commentreport_user_donation_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
